pipeline:
  tests:
    image: python:2.7
    commands:
      - pip install --no-cache-dir --upgrade pip setuptools wheel flake8
      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
      - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
      - flake8 oca/tests
      - python -m unittest discover

  build-package:
    image: registry.databus.systems/drone-plugins/drone-devpi
    server: https://devpi.databus.systems
    index: root/opensource
    username: ${OPENSOURCE_DEVPI_USER}
    password: ${OPENSOURCE_DEVPI_PASSWORD}

  notify-slack:
    image: plugins/slack
    webhook: ${SLACK_HOOK}
    when:
     status: [ success, failure ]
