pipeline:
  test:
    image: python:2.7-alpine
    commands:
      - pip install --no-cache-dir --upgrade pip setuptools wheel
      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
      - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
      - python -m unittest autodiscover

